### ISSUE TITLE
plz solve this error...

### ISSUE THREAD

**Issue by Rushikesh207** [abhishek-mygit/Cricket-Match-Win-Predictor#1]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "PredictTheOutComeUI.py", line 495, in predict
    bat_ground_1,ball_ground_1 = getStats.stats(team1,ground,date)
  File "C:\Users\rushikesh\Desktop\New Folder (3)\Cricket-Match-Win-Predictor-master\getStats.py", line 284, in stats
    team_Batsman = SingleBatsman(team[i][0],team[i][1],ground_id,date)
  File "C:\Users\rushikesh\Desktop\New Folder (3)\Cricket-Match-Win-Predictor-master\getStats.py", line 221, in SingleBatsman
    Mined_Single_Player_Stats = MakeDataFrameBatsman(url)  #Stats Mined from Web
  File "C:\Users\rushikesh\Desktop\New Folder (3)\Cricket-Match-Win-Predictor-master\getStats.py", line 75, in MakeDataFrameBatsman
    D.append(float(TeamScore))
ValueError: could not convert string to float: []

**Comment by codemonkfromait** [comment]
is this issue resolved i have the same problem can anyone help

**Comment by abhishek-mygit** [comment]
Hi, this is a project that was developed around 2 years back. And it works on scraping data from web. Please do first ensure if the websites (like ESPN CricInfo STATSGURU) still maintain the same URL format to display the results to the users. If so, this code should absolutely work fine. Or else, you must reconstruct the URL as per new standards.

The issue in your screenshot says string to float conversion error. Then there might be any alpha characters in the TeamScore variable. Comment the value of TeamScore if possible. First, try printing the TeamScore value and check what value it contains and please ensure if it has only numeric characters. If not, then website should either have changed the URL format or should have changed the division IDs or divison class names from which the code retrieves the content. Due to which, the code might scrap the undesired content. In this case, you might need to inspect the present webpage and feed in the current correct tag identifiers.

It is better to print and check if all the critical variables retrieve only the desired data. This will help you ensure if the web pages are still maintained in the same way. Else, you can proceed to make the necessary changes.
