### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Finnt404** [abhishek-mygit/Cricket-Match-Win-Predictor#2]
![RoR](https://user-images.githubusercontent.com/53485302/66581698-32229c80-eb9e-11e9-8d72-50c5c196a344.png)
please help me out!!

**Comment by abhishek-mygit** [comment]
Hi.. Sorry for late reply..
Instead of the ground name, the ground id is needed to be entered which could be found using the ESPN Cricinfo Statsguru page. The following is the link for the same. 

http://stats.espncricinfo.com/ci/engine/stats/index.html

After navigating to the website, under the 'Statsguru Records' section or anchor, if you click any format of cricket once you fill the ground name and submit, you could easily find the ground id for that particular ground that ESPNCricinfo uses on its back-end database. For example, the ground id here for Chepauk stadium is 291. In this way, you have to enter the ground id of the the ground that you desire.

This is because, this project entirely depends on data scraping from the website and we have no other option of building the URL of the website from which we need to scrap the data. The following images will give you an idea of how to find the ground id. 

<img width="960" alt="Form to fill out Ground Id" src="https://user-images.githubusercontent.com/39903580/70904197-ca1d8600-2026-11ea-8316-565388b68804.PNG">

<img width="960" alt="Ground ID Visible" src="https://user-images.githubusercontent.com/39903580/70904521-9bec7600-2027-11ea-8862-53738f4938ed.PNG">

**Comment by Finnt404** [comment]
Thank u so much ✌️

**Comment by Finnt404** [comment]
Thank you so much ✌️
